// AQA GCSE Physics 8463-style prompts grouped by typing difficulty.
// Keep terms concise; definitions appear as hints in later rounds.
// Medium and hard terms become boss questions, where the definition is the clue and
// part of the term is hidden, so a definition should not repeat the words of its term.
export const EASY_WORDS = [
  // Quantities & units
  { term: 'force', definition: 'A push or pull that may change speed, shape or direction' },
  { term: 'mass', definition: 'The amount of matter in an object, measured in kilograms' },
  { term: 'weight', definition: 'The force on a mass due to gravity' },
  { term: 'speed', definition: 'Distance travelled per unit time' },
  { term: 'velocity', definition: 'Speed in a specified direction' },
  { term: 'distance', definition: 'How far an object has moved' },
  { term: 'time', definition: 'How long an event lasts, measured in seconds' },
  { term: 'length', definition: 'The distance from one end of an object to the other' },
  { term: 'height', definition: 'Vertical distance above a surface' },
  { term: 'area', definition: 'The size of a surface, measured in square metres' },
  { term: 'volume', definition: 'The amount of space an object takes up' },
  { term: 'energy', definition: 'The capacity to do work or heat an object, measured in joules' },
  { term: 'joule', definition: 'The unit of energy and work done' },
  { term: 'power', definition: 'The rate at which energy is transferred' },
  { term: 'watt', definition: 'The unit of power, equal to one joule per second' },
  { term: 'newton', definition: 'The unit of force' },
  { term: 'kilogram', definition: 'The SI unit of mass' },
  { term: 'pascal', definition: 'The unit of pressure, equal to one newton per square metre' },
  { term: 'hertz', definition: 'The unit of frequency, equal to one wave per second' },
  { term: 'density', definition: 'Mass per unit volume' },
  { term: 'pressure', definition: 'Force per unit area' },
  { term: 'temperature', definition: 'A measure of the average kinetic energy of the particles' },
  { term: 'kelvin', definition: 'The SI unit of temperature; 0 K is absolute zero' },
  // Forces
  { term: 'gravity', definition: 'The force of attraction between all masses' },
  { term: 'tension', definition: 'The pulling force in a stretched rope, string or spring' },
  { term: 'moment', definition: 'The turning effect of a force' },
  { term: 'pivot', definition: 'The point about which an object turns' },
  { term: 'lever', definition: 'A simple machine that turns about a pivot' },
  { term: 'gear', definition: 'A toothed wheel that transmits the turning effect of a force' },
  // Electricity
  { term: 'current', definition: 'The rate of flow of electric charge' },
  { term: 'charge', definition: 'A property of particles; positive or negative, measured in coulombs' },
  { term: 'coulomb', definition: 'The SI unit of electric charge' },
  { term: 'ampere', definition: 'The unit of electric current' },
  { term: 'volt', definition: 'The unit of potential difference' },
  { term: 'ohm', definition: 'The unit of resistance' },
  { term: 'resistance', definition: 'How much a component opposes current' },
  { term: 'circuit', definition: 'A complete path that electric current can flow around' },
  { term: 'cell', definition: 'A single source of potential difference in a circuit' },
  { term: 'battery', definition: 'Two or more cells connected together' },
  { term: 'switch', definition: 'A component that opens or closes a circuit' },
  { term: 'resistor', definition: 'A component used to limit the current in a circuit' },
  { term: 'ammeter', definition: 'A meter connected in series to measure current' },
  { term: 'voltmeter', definition: 'A meter connected in parallel to measure potential difference' },
  { term: 'LDR', definition: 'A resistor whose resistance changes with light intensity' },
  { term: 'fuse', definition: 'A safety device that melts to break the circuit if current is too high' },
  // Particles & atoms
  { term: 'solid', definition: 'A state of matter with fixed shape and volume' },
  { term: 'liquid', definition: 'A state of matter with fixed volume but changing shape' },
  { term: 'gas', definition: 'A state of matter with no fixed shape or volume' },
  { term: 'fluid', definition: 'A substance that can flow; a liquid or a gas' },
  { term: 'melting', definition: 'The change of state from solid to liquid' },
  { term: 'freezing', definition: 'The change of state from liquid to solid' },
  { term: 'boiling', definition: 'The change of state from liquid to gas throughout the liquid' },
  { term: 'atom', definition: 'The smallest part of an element that can exist' },
  { term: 'nucleus', definition: 'The small central part of an atom' },
  { term: 'proton', definition: 'A positively charged particle in the nucleus' },
  { term: 'neutron', definition: 'An uncharged particle in the nucleus' },
  { term: 'electron', definition: 'A negatively charged particle around the nucleus' },
  { term: 'isotope', definition: 'Atoms of the same element with different numbers of neutrons' },
  { term: 'alpha', definition: 'A type of nuclear radiation made of two protons and two neutrons' },
  { term: 'beta', definition: 'A type of nuclear radiation made of a fast moving electron from the nucleus' },
  { term: 'gamma', definition: 'A high frequency electromagnetic wave from the nucleus' },
  { term: 'becquerel', definition: 'The unit of activity, equal to one decay per second' },
  { term: 'sievert', definition: 'The unit of radiation dose' },
  // Waves & light
  { term: 'wave', definition: 'A disturbance that transfers energy without transferring matter' },
  { term: 'sound', definition: 'A longitudinal wave caused by vibrations' },
  { term: 'light', definition: 'Electromagnetic radiation visible to the eye' },
  { term: 'reflection', definition: 'The bouncing of waves back from a surface' },
  { term: 'normal', definition: 'A line perpendicular to a surface at the point where a ray meets it' },
  { term: 'ray', definition: 'A line showing the direction light travels' },
  { term: 'mirror', definition: 'A polished surface that reflects light rays specularly' },
  { term: 'lens', definition: 'A piece of curved glass or plastic that refracts light' },
  { term: 'prism', definition: 'A triangular glass block that disperses light into a spectrum' },
  { term: 'spectrum', definition: 'The band of colours produced when white light is dispersed' },
  { term: 'echo', definition: 'A reflected sound wave' },
  { term: 'pitch', definition: 'How high or low a sound is, determined by wave frequency' },
  { term: 'crest', definition: 'The highest point of a transverse wave' },
  { term: 'trough', definition: 'The lowest point of a transverse wave' },
  { term: 'period', definition: 'The time taken for one complete wave to pass a point' },
  { term: 'P waves', definition: 'Longitudinal seismic waves that travel through solids and liquids' },
  { term: 'S waves', definition: 'Transverse seismic waves that cannot travel through liquids' },
  { term: 'vacuum', definition: 'A space entirely empty of matter where sound cannot travel' },
  { term: 'conduction', definition: 'Heat transfer through a solid by particle vibration and collision' },
  { term: 'convection', definition: 'Heat transfer through a fluid by the bulk movement of particles' },
  // Magnetism
  { term: 'magnet', definition: 'An object that produces a magnetic field' },
  { term: 'field', definition: 'A region where a non-contact force acts' },
  { term: 'pole', definition: 'The part of a magnet where the magnetic force is strongest' },
  { term: 'compass', definition: 'A small magnet that points along the magnetic field direction' },
  { term: 'tesla', definition: 'The unit of magnetic flux density' },
  // Space
  { term: 'orbit', definition: 'The curved path of an object around a star, planet or moon' },
  { term: 'star', definition: 'A huge ball of gas that releases energy by nuclear fusion' },
  { term: 'planet', definition: 'A large body that orbits a star' },
  { term: 'moon', definition: 'A natural satellite of a planet' },
  { term: 'satellite', definition: 'An object that orbits a planet' },
  { term: 'galaxy', definition: 'A large system of stars, gas and dust held together by gravity' },
  { term: 'universe', definition: 'Everything that exists: all space, matter and energy' },
];

export const MEDIUM_WORDS = [
  // Energy
  { term: 'energy store', definition: 'Kinetic, thermal, chemical or gravitational potential, for example' },
  { term: 'work done', definition: 'Energy transferred when a force moves an object' },
  { term: 'efficiency', definition: 'Useful energy output divided by total energy input' },
  { term: 'dissipation', definition: 'The spreading out of energy into the surroundings so it is less useful' },
  { term: 'closed system', definition: 'A set of objects with no net energy transfer in or out' },
  { term: 'insulation', definition: 'Material used to reduce unwanted energy transfer by heating' },
  { term: 'lubricant', definition: 'A substance reducing friction between moving surfaces' },
  { term: 'renewable', definition: 'An energy resource that can be replaced as it is used' },
  { term: 'non renewable', definition: 'An energy resource that will run out' },
  { term: 'fossil fuels', definition: 'Coal, oil and gas formed from the remains of ancient organisms' },
  { term: 'biofuel', definition: 'A renewable fuel made from recently living plant or animal matter' },
  { term: 'geothermal', definition: 'An energy resource using hot rocks underground' },
  { term: 'hydroelectric', definition: 'An energy resource using water falling from a reservoir' },
  { term: 'solar cell', definition: 'A device that transfers energy from sunlight directly to electricity' },
  { term: 'wind turbine', definition: 'A generator turned by moving air' },
  { term: 'national grid', definition: 'The network transferring electricity from power stations to users' },
  // Electricity
  { term: 'potential difference', definition: 'Energy transferred per unit charge' },
  { term: 'charge flow', definition: 'Current multiplied by time; measured in coulombs' },
  { term: 'power rating', definition: 'The energy an appliance transfers each second' },
  { term: 'ohmic conductor', definition: 'Current is directly proportional to potential difference at constant temperature' },
  { term: 'filament lamp', definition: 'A bulb whose resistance rises as its wire gets hotter' },
  { term: 'thermistor', definition: 'A resistor whose resistance changes with temperature' },
  { term: 'diode', definition: 'A component that allows current to flow in one direction only' },
  { term: 'conductor', definition: 'A material that allows heat or electricity to pass through easily' },
  { term: 'insulator', definition: 'A material that does not allow heat or electricity to pass easily' },
  { term: 'direct current', definition: 'A flow of charge that always travels in the same direction' },
  { term: 'alternating current', definition: 'A flow of charge that repeatedly reverses direction' },
  { term: 'live wire', definition: 'The brown mains conductor, at about 230 V' },
  { term: 'neutral wire', definition: 'The blue mains conductor, at about 0 V, that completes the circuit' },
  { term: 'earth wire', definition: 'The green and yellow safety conductor that carries fault current to ground' },
  // Thermal & particle model
  { term: 'particle model', definition: 'A way to explain states of matter using tiny moving spheres' },
  { term: 'change of state', definition: 'Melting, boiling, freezing or condensing, for example' },
  { term: 'physical change', definition: 'Reversible, and no new substances are formed' },
  { term: 'evaporation', definition: 'Change from liquid to gas at the surface, below the boiling point' },
  { term: 'condensation', definition: 'The change of state from gas to liquid' },
  { term: 'sublimation', definition: 'The change of state from solid directly to gas' },
  { term: 'melting point', definition: 'The temperature at which a solid turns into a liquid' },
  { term: 'boiling point', definition: 'The temperature at which bubbles of gas form throughout a liquid' },
  { term: 'latent heat', definition: 'Energy to change state without changing temperature' },
  { term: 'internal energy', definition: 'The total kinetic and potential stores of all the particles in a system' },
  { term: 'absolute zero', definition: 'The lowest possible temperature, equal to 0 K or −273 °C' },
  { term: 'gas pressure', definition: 'Force per unit area from particles colliding with walls' },
  // Atomic & nuclear
  { term: 'atomic number', definition: 'How many protons a nucleus contains' },
  { term: 'mass number', definition: 'How many protons and neutrons a nucleus contains in total' },
  { term: 'energy level', definition: 'One of the fixed distances from the nucleus at which electrons orbit' },
  { term: 'nuclear model', definition: 'The atom as a tiny positive centre with electrons orbiting around it' },
  { term: 'alpha scattering', definition: 'Experiment firing particles at gold foil that revealed the nucleus' },
  { term: 'alpha particle', definition: 'Two protons and two neutrons emitted together; a helium nucleus' },
  { term: 'beta particle', definition: 'A fast electron emitted when a neutron turns into a proton' },
  { term: 'half life', definition: 'Time for the count rate, or number of unstable nuclei, to halve' },
  { term: 'activity', definition: 'The rate at which unstable nuclei decay' },
  { term: 'radioactive decay', definition: 'Spontaneous emission of radiation from an unstable nucleus' },
  { term: 'random', definition: 'Describes decay: nobody can predict which nucleus will go next' },
  { term: 'count rate', definition: 'The number of decays recorded each second by a detector' },
  { term: 'ionising radiation', definition: 'Emissions that can knock electrons out of atoms' },
  { term: 'radiation dose', definition: 'A measure of the risk of harm from exposure, in sieverts' },
  { term: 'irradiation', definition: 'Exposing an object to nuclear radiation without making it radioactive' },
  { term: 'contamination', definition: 'Unwanted radioactive material on or inside an object' },
  { term: 'tracer', definition: 'A radioactive isotope used to follow a substance through the body' },
  // Forces & motion
  { term: 'scalar', definition: 'A quantity with magnitude only' },
  { term: 'vector', definition: 'A quantity with magnitude and direction' },
  { term: 'displacement', definition: 'Distance in a straight line from start to finish, with its direction' },
  { term: 'average speed', definition: 'Total distance travelled divided by total time taken' },
  { term: 'acceleration', definition: 'Rate of change of velocity' },
  { term: 'deceleration', definition: 'The rate at which an object slows down' },
  { term: 'gradient', definition: 'The steepness of a line on a graph' },
  { term: 'contact force', definition: 'An interaction that acts only when two objects are touching' },
  { term: 'non contact force', definition: 'An interaction between objects that are physically separated' },
  { term: 'resultant force', definition: 'The single push or pull with the same effect as all the others combined' },
  { term: 'free body diagram', definition: 'Arrows drawn on a single object to show everything acting on it' },
  { term: 'friction', definition: 'A force opposing motion between surfaces' },
  { term: 'drag', definition: 'Resistive force on an object moving through a fluid' },
  { term: 'air resistance', definition: 'The drag on an object moving through the atmosphere' },
  { term: 'upthrust', definition: 'Upward force a fluid exerts on an object floating or submerged in it' },
  { term: 'equilibrium', definition: 'State in which the resultant force and resultant moment are both zero' },
  { term: 'momentum', definition: 'Mass multiplied by velocity' },
  { term: 'deformation', definition: 'A change in shape of a material caused by an applied force' },
  { term: 'extension', definition: 'Increase in length of a stretched object' },
  { term: 'spring constant', definition: 'The force needed per metre of extension; a measure of stiffness' },
  { term: 'Hooke\'s law', definition: 'Extension is directly proportional to force, up to a limit' },
  { term: 'stopping distance', definition: 'Thinking plus braking: how far a car travels before it comes to rest' },
  { term: 'reaction time', definition: 'How long a person takes to respond to a stimulus' },
  { term: 'crumple zone', definition: 'Car safety feature that lengthens a collision to reduce the force' },
  // Waves
  { term: 'frequency', definition: 'Number of complete waves passing a point each second' },
  { term: 'wavelength', definition: 'Distance from a point on one wave to the same point on the next' },
  { term: 'amplitude', definition: 'Maximum displacement from the undisturbed position' },
  { term: 'wave speed', definition: 'How fast energy is transferred through a medium' },
  { term: 'oscillation', definition: 'A repeated back and forth movement about a fixed position' },
  { term: 'transverse wave', definition: 'Oscillations are perpendicular to the direction of energy transfer' },
  { term: 'longitudinal wave', definition: 'Oscillations are parallel to the direction of energy transfer' },
  { term: 'compression', definition: 'Region of high pressure in a longitudinal wave' },
  { term: 'rarefaction', definition: 'Region of low pressure in a longitudinal wave' },
  { term: 'ripple tank', definition: 'Shallow tray of water used to observe wave behaviour' },
  { term: 'absorption', definition: 'Transfer of energy from a wave into the medium it passes through' },
  { term: 'transmission', definition: 'When a wave carries on travelling through a material' },
  { term: 'refraction', definition: 'Change of direction when a wave changes speed at a boundary' },
  { term: 'diffraction', definition: 'Spreading of waves through gaps or around obstacles' },
  { term: 'dispersion', definition: 'Splitting white light into colours because each refracts differently' },
  { term: 'ultrasound', definition: 'Sound with a frequency above 20 kHz, too high for humans to hear' },
  { term: 'echo sounding', definition: 'Using reflected high frequency pulses to measure the depth of water' },
  { term: 'seismic waves', definition: 'Vibrations from earthquakes that travel through the Earth' },
  // Light
  { term: 'ray diagram', definition: 'A drawing of straight lines showing the path of light' },
  { term: 'incident ray', definition: 'Light travelling towards a boundary or surface' },
  { term: 'refracted ray', definition: 'Light that has changed direction on crossing a boundary' },
  { term: 'reflected ray', definition: 'Light that has bounced off a surface' },
  { term: 'convex lens', definition: 'Converges parallel light to a principal focus; thicker in the middle' },
  { term: 'concave lens', definition: 'Diverges parallel light; thinner in the middle' },
  { term: 'principal focus', definition: 'The point where rays parallel to the axis meet after a convex lens' },
  { term: 'focal length', definition: 'Distance from the centre of a lens to its principal focus' },
  { term: 'real image', definition: 'Formed where light rays actually meet; can be projected on a screen' },
  { term: 'virtual image', definition: 'Formed where light rays only appear to come from; cannot be projected' },
  { term: 'transparent', definition: 'Describes an object that transmits light without scattering it' },
  { term: 'translucent', definition: 'Describes an object that transmits light but scatters it' },
  { term: 'opaque', definition: 'Describes an object that does not transmit light' },
  { term: 'colour filter', definition: 'Absorbs some wavelengths of light and transmits others' },
  // Magnetism
  { term: 'magnetic field', definition: 'The region around a magnet where iron or steel experiences a force' },
  { term: 'induced magnet', definition: 'A material that is magnetic only while placed in a magnetic field' },
  { term: 'solenoid', definition: 'A coil of wire that produces a magnetic field when carrying current' },
  { term: 'electromagnet', definition: 'A magnet produced by current in a coil' },
  { term: 'iron core', definition: 'The magnetic centre of a transformer or electromagnet' },
  { term: 'motor effect', definition: 'Force on a current-carrying wire in a magnetic field' },
  { term: 'electric motor', definition: 'A coil in a magnetic field that spins when current passes through it' },
  { term: 'alternator', definition: 'A generator that produces alternating current' },
  { term: 'dynamo', definition: 'A generator that produces direct current' },
  { term: 'loudspeaker', definition: 'Uses the motor effect to turn current variations into sound waves' },
  { term: 'microphone', definition: 'Uses the generator effect to turn sound waves into current variations' },
  { term: 'primary coil', definition: 'The part of a transformer connected to the alternating supply' },
  { term: 'secondary coil', definition: 'The part of a transformer in which a potential difference is induced' },
  // Space
  { term: 'solar system', definition: 'The Sun and all the objects that orbit it' },
  { term: 'dwarf planet', definition: 'A small round body orbiting the Sun, such as Pluto' },
  { term: 'Milky Way', definition: 'The galaxy that contains our solar system' },
  { term: 'circular orbit', definition: 'A path in which speed is constant but velocity keeps changing' },
  { term: 'nebula', definition: 'A cloud of gas and dust in space where stars can form' },
  { term: 'protostar', definition: 'An early stage of star formation from a collapsing nebula' },
  { term: 'red shift', definition: 'Increase in the wavelength of light from a galaxy moving away' },
  { term: 'dark matter', definition: 'Unseen mass thought to hold galaxies together' },
  { term: 'dark energy', definition: 'Unknown cause proposed for the accelerating expansion of the universe' },
];

export const HARD_WORDS = [
  // Energy
  { term: 'gravitational potential energy', definition: 'Stored by an object because of its height above the ground' },
  { term: 'kinetic energy', definition: 'The store an object has because it is moving' },
  { term: 'thermal energy', definition: 'The store that increases when a substance is heated' },
  { term: 'elastic potential energy', definition: 'Stored in an object that is stretched, squashed or bent' },
  { term: 'specific heat capacity', definition: 'Energy to raise the temperature of 1 kg of a substance by 1 °C' },
  { term: 'specific latent heat', definition: 'Energy to change the state of 1 kg with no change in temperature' },
  { term: 'specific latent heat of fusion', definition: 'Energy to change 1 kg from solid to liquid at constant temperature' },
  { term: 'specific latent heat of vaporisation', definition: 'Energy to change 1 kg from liquid to gas at constant temperature' },
  { term: 'thermal conductivity', definition: 'A measure of how quickly energy passes through a material by heating' },
  // Electricity
  { term: 'static electricity', definition: 'Charge build-up caused by electrons moving between insulators' },
  { term: 'electric field', definition: 'A region where a charged object experiences a force' },
  { term: 'series circuit', definition: 'Components on a single loop, so the current is the same everywhere' },
  { term: 'parallel circuit', definition: 'Components on separate branches, each with the same potential difference' },
  { term: 'variable resistor', definition: 'A component adjusted by hand to change the current in a circuit' },
  { term: 'light dependent resistor', definition: 'A component whose resistance falls as its surroundings get brighter' },
  { term: 'light emitting diode', definition: 'A component that glows when current passes through it the right way' },
  { term: 'mains electricity', definition: 'The 230 V, 50 Hz alternating supply to homes in the UK' },
  // Nuclear
  { term: 'plum pudding model', definition: 'Early idea of the atom: a ball of positive charge with electrons embedded' },
  { term: 'Geiger Muller tube', definition: 'A detector used to measure count rate from a radioactive source' },
  { term: 'nuclear fission', definition: 'Splitting a large unstable nucleus into smaller nuclei' },
  { term: 'nuclear fusion', definition: 'Joining small nuclei to form a larger nucleus' },
  { term: 'chain reaction', definition: 'Fission neutrons causing more nuclei to split' },
  { term: 'control rods', definition: 'Lowered into a reactor to absorb neutrons and slow the chain reaction' },
  { term: 'moderator', definition: 'A material in a nuclear reactor that slows down fission neutrons' },
  { term: 'background radiation', definition: 'Low level ionising emissions always present, from rocks and cosmic rays' },
  // Forces & motion
  { term: 'Newton\'s first law', definition: 'An object stays at rest or constant velocity unless a resultant force acts' },
  { term: 'Newton\'s second law', definition: 'Resultant force equals mass multiplied by acceleration' },
  { term: 'Newton\'s third law', definition: 'When two objects interact, their forces on each other are equal and opposite' },
  { term: 'normal contact force', definition: 'The support from a surface, acting at right angles to it' },
  { term: 'gravitational field strength', definition: 'The weight of each kilogram at a point; about 9.8 N/kg on Earth' },
  { term: 'terminal velocity', definition: 'The constant speed reached when the resultant force becomes zero' },
  { term: 'uniform acceleration', definition: 'Velocity changing by the same amount every second' },
  { term: 'distance time graph', definition: 'Its gradient gives the speed of the object' },
  { term: 'velocity time graph', definition: 'Its gradient gives acceleration; the area under it gives how far' },
  { term: 'inertial mass', definition: 'Measure of how difficult it is to change velocity' },
  { term: 'conservation of momentum', definition: 'The total of mass × velocity is unchanged by a collision in a closed system' },
  { term: 'centre of mass', definition: 'The point through which an object\'s weight appears to act' },
  { term: 'principle of moments', definition: 'For a balanced object, total clockwise turning effect equals anticlockwise' },
  { term: 'limit of proportionality', definition: 'The point beyond which Hooke\'s law is no longer obeyed' },
  { term: 'elastic deformation', definition: 'The object returns to its original shape when the force is removed' },
  { term: 'inelastic deformation', definition: 'The object stays permanently changed in shape after the force is removed' },
  { term: 'thinking distance', definition: 'How far a vehicle travels during the driver\'s reaction time' },
  { term: 'braking distance', definition: 'How far a vehicle travels from pressing the pedal until it stops' },
  { term: 'atmospheric pressure', definition: 'Force per unit area caused by the weight of the air above' },
  // Waves
  { term: 'wave equation', definition: 'Speed equals frequency multiplied by wavelength' },
  { term: 'angle of incidence', definition: 'Measured between the incoming ray and the normal' },
  { term: 'angle of refraction', definition: 'Measured between the ray inside the new medium and the normal' },
  { term: 'critical angle', definition: 'The incidence above which total internal reflection occurs' },
  { term: 'total internal reflection', definition: 'All the light stays inside the denser medium beyond the critical angle' },
  { term: 'specular reflection', definition: 'Light bouncing off a smooth surface in a single direction' },
  { term: 'diffuse reflection', definition: 'Light bouncing off a rough surface and scattering in all directions' },
  { term: 'electromagnetic wave', definition: 'A transverse oscillation that can travel through a vacuum' },
  { term: 'electromagnetic spectrum', definition: 'The family of waves from radio to gamma, in order of frequency' },
  { term: 'radio waves', definition: 'The electromagnetic radiation with the longest wavelength and lowest frequency' },
  { term: 'microwaves', definition: 'Electromagnetic waves used for satellite communication and heating food' },
  { term: 'infrared', definition: 'Radiation between microwaves and visible light, emitted by all objects' },
  { term: 'visible light', definition: 'The only part of the electromagnetic spectrum that human eyes detect' },
  { term: 'ultraviolet', definition: 'Radiation between visible light and X-rays; causes sunburn' },
  { term: 'x rays', definition: 'High-energy electromagnetic waves used for medical imaging' },
  { term: 'gamma rays', definition: 'Electromagnetic radiation with the shortest wavelength and highest frequency' },
  { term: 'perfect black body', definition: 'An object that absorbs all the radiation that falls on it' },
  // Magnetism & induction
  { term: 'permanent magnet', definition: 'Produces its own magnetic field all the time' },
  { term: 'magnetic flux density', definition: 'The strength of a field, measured in tesla' },
  { term: 'Fleming\'s left hand rule', definition: 'Uses thumb and two fingers to find the direction of the force on a wire' },
  { term: 'split ring commutator', definition: 'Reverses the current in a motor coil every half turn' },
  { term: 'generator effect', definition: 'A potential difference induced when a conductor cuts magnetic field lines' },
  { term: 'electromagnetic induction', definition: 'Producing a potential difference by changing the magnetic field through a coil' },
  { term: 'induced potential difference', definition: 'Produced across a conductor when it cuts magnetic field lines' },
  { term: 'transformer', definition: 'Device changing alternating potential difference using induction' },
  { term: 'step up transformer', definition: 'Has more turns on its secondary coil, so potential difference increases' },
  { term: 'step down transformer', definition: 'Has fewer turns on its secondary coil, so potential difference decreases' },
  // Space
  { term: 'artificial satellite', definition: 'A human-made object placed in orbit around a planet' },
  { term: 'main sequence', definition: 'Stable star stage where fusion balances gravity' },
  { term: 'red giant', definition: 'A star that has expanded after exhausting hydrogen fuel in its core' },
  { term: 'red supergiant', definition: 'A massive star that has swollen after its main sequence stage' },
  { term: 'white dwarf', definition: 'The hot dense core left when a Sun-like star sheds its outer layers' },
  { term: 'black dwarf', definition: 'A star remnant that has cooled and no longer emits light' },
  { term: 'supernova', definition: 'The explosion marking the end of a massive star\'s life' },
  { term: 'neutron star', definition: 'The extremely dense core left behind after a supernova' },
  { term: 'black hole', definition: 'A region of space where gravity is too strong for even light to escape' },
  { term: 'big bang', definition: 'Theory that the universe began from a very hot dense state' },
  { term: 'cosmic microwave background radiation', definition: 'Faint glow left over from the early universe; evidence for the Big Bang' },
];

export const ALL_WORDS = [...EASY_WORDS, ...MEDIUM_WORDS, ...HARD_WORDS];

// AQA GCSE Physics 8463 word equations — used for the equation boss each wave.
// term = the word equation the player types; definition = compact symbolic form shown on label.
export const EQUATION_WORDS = [
  // Forces & motion
  { term: 'weight = mass × gravitational field strength', definition: 'W = mg', isEquation: true },
  { term: 'resultant force = mass × acceleration', definition: 'F = ma', isEquation: true },
  { term: 'work done = force × distance', definition: 'W = Fs', isEquation: true },
  { term: 'distance travelled = speed × time', definition: 's = vt', isEquation: true },
  { term: 'acceleration = change in velocity / time taken', definition: 'a = Δv / t', isEquation: true },
  { term: 'momentum = mass × velocity', definition: 'p = mv', isEquation: true },
  { term: 'force = change in momentum / time taken', definition: 'F = mΔv / Δt', isEquation: true },
  { term: 'moment of a force = force × distance', definition: 'M = Fd', isEquation: true },
  { term: 'force = spring constant × extension', definition: 'F = ke', isEquation: true },
  { term: 'final velocity² − initial velocity² = 2 × acceleration × distance', definition: 'v² − u² = 2as', isEquation: true },

  // Energy
  { term: 'kinetic energy = 0.5 × mass × speed²', definition: 'Ek = ½mv²', isEquation: true },
  { term: 'gravitational potential energy = mass × gravitational field strength × height', definition: 'Ep = mgh', isEquation: true },
  { term: 'elastic potential energy = 0.5 × spring constant × extension²', definition: 'Ee = ½ke²', isEquation: true },
  { term: 'power = energy transferred / time', definition: 'P = E / t', isEquation: true },
  { term: 'power = work done / time', definition: 'P = W / t', isEquation: true },
  { term: 'energy transferred = power × time', definition: 'E = Pt', isEquation: true },
  { term: 'efficiency = useful power output / total power input', definition: 'efficiency = Pout / Pin', isEquation: true },
  { term: 'efficiency = useful output energy transfer / total input energy transfer', definition: 'efficiency = Eout / Ein', isEquation: true },

  // Materials & pressure
  { term: 'density = mass / volume', definition: 'ρ = m / V', isEquation: true },
  { term: 'pressure = force / area', definition: 'p = F / A', isEquation: true },
  { term: 'pressure = height × density × gravitational field strength', definition: 'p = hρg', isEquation: true },
  { term: 'pressure × volume = constant', definition: 'pV = constant', isEquation: true },

  // Thermal
  { term: 'change in thermal energy = mass × specific heat capacity × temperature change', definition: 'ΔE = mcΔθ', isEquation: true },
  { term: 'thermal energy for a change of state = mass × specific latent heat', definition: 'E = mL', isEquation: true },

  // Waves & light
  { term: 'wave speed = frequency × wavelength', definition: 'v = fλ', isEquation: true },
  { term: 'period = 1 / frequency', definition: 'T = 1 / f', isEquation: true },
  { term: 'magnification = image height / object height', definition: 'magnification = hi / ho', isEquation: true },

  // Electricity
  { term: 'charge flow = current × time', definition: 'Q = It', isEquation: true },
  { term: 'potential difference = current × resistance', definition: 'V = IR', isEquation: true },
  { term: 'power = potential difference × current', definition: 'P = VI', isEquation: true },
  { term: 'power = current² × resistance', definition: 'P = I²R', isEquation: true },
  { term: 'energy transferred = charge flow × potential difference', definition: 'E = QV', isEquation: true },

  // Magnetism & induction
  { term: 'force = magnetic flux density × current × length', definition: 'F = BIl', isEquation: true },
  { term: 'primary potential difference / secondary potential difference = primary turns / secondary turns', definition: 'Vp / Vs = np / ns', isEquation: true },
  { term: 'primary potential difference × primary current = secondary potential difference × secondary current', definition: 'VpIp = VsIs', isEquation: true },
];
