'use strict';
const STORAGE_KEY = 'panphy-physics-launch-v1';
const state = { mission: 0, answers: {}, solved: {}, notes: {} };
let storageAvailable = true;
try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (saved && typeof saved === 'object') { if(Number.isInteger(saved.mission) && saved.mission >= 0 && saved.mission < 6) state.mission=saved.mission; for (const key of ['answers','solved','notes']) if(saved[key] && typeof saved[key]==='object' && !Array.isArray(saved[key])) state[key]=saved[key]; } } catch { storageAvailable = false; }
const questions = {};
function mc(id, prompt, options, correct, explanation) { questions[id] = { id, prompt, options, correct, explanation, type:'mc' }; return id; }
function numeric(id, prompt, correct, unit, explanation) { questions[id] = { id, prompt, correct, unit, explanation, type:'number' }; return id; }
const missions = [
{title:'Decode the course', short:'Course briefing', time:'10 min', kicker:'01 / RECON', intro:'Meet the course you are about to explore. SL and HL share the same scientific habits; HL travels further and deeper.', content:()=>`
<div class="card read"><h3>Guide hunt · 3 minutes</h3><p>Open <a href="physics-guide-2025.pdf#page=16" target="_blank" rel="noopener">printed page 10 (PDF page 16)</a> and <a href="physics-guide-2025.pdf#page=30" target="_blank" rel="noopener">printed page 24 (PDF page 30)</a>. Find one thing SL and HL share and one difference. Then test yourself below.</p><p class="small muted">Links use PDF viewer page numbers; printed page numbers are six lower. If your viewer ignores the link, type the PDF page number into its page box.</p></div>
<div class="card"><h3>The course, decoded</h3><div class="grid"><div class="tile"><strong>SL · Standard level</strong><div class="stat">150 h</div><p>A foundation in physics, with theory, practical work and an individual investigation.</p></div><div class="tile"><strong>HL · Higher level</strong><div class="stat">240 h</div><p>Additional content and greater conceptual depth, with more connections between topics.</p></div></div><p class="small muted">Recommended teaching hours, including the experimental programme.</p><h3>Five connected territories</h3><p><b>A</b> Space, time and motion · <b>B</b> The particulate nature of matter · <b>C</b> Wave behaviour · <b>D</b> Fields · <b>E</b> Nuclear and quantum physics</p><p>Both levels include practical work, a collaborative sciences project and one scientific investigation. Being a physicist means testing ideas against evidence, not just memorising equations.</p><p class="small muted">Summary: guide pp. 10 and 24. All lesson summaries are paraphrases.</p></div>`, ids:[
mc('shared','Which experience belongs to BOTH SL and HL?', ['An individual scientific investigation','Exactly 240 recommended teaching hours','Only multiple-choice examinations'],0,'Both levels complete one scientific investigation, practical work and a collaborative sciences project. HL adds breadth and depth.'),
numeric('hours','How many more recommended teaching hours does HL have than SL?',90,'hours','240 − 150 = 90 hours. This includes additional syllabus content and practical work.'),
mc('themes','A question about gravitational attraction fits most directly into which territory?', ['Wave behaviour','Fields','The particulate nature of matter'],1,'Gravitational, electric and magnetic interactions are explored through fields. The territories also connect to each other.') ]},
{title:'Crack the assessment code',short:'Assessment intel',time:'10 min',kicker:'02 / INTEL',intro:'Know the map before you set off. Find out what the exams assess—and what makes the investigation your own.',content:()=>`
<div class="card read"><h3>Guide hunt · 4 minutes</h3><p>Read <a href="physics-guide-2025.pdf#page=68" target="_blank" rel="noopener">assessment outlines, pp. 62–63 (PDF 68–69)</a>. Then scan <a href="physics-guide-2025.pdf#page=74" target="_blank" rel="noopener">the investigation, pp. 68–69 (PDF 74–75)</a> and <a href="physics-guide-2025.pdf#page=78" target="_blank" rel="noopener">criteria, p. 72 (PDF 78)</a>. Look for the weightings, report limit and four criteria.</p></div>
<div class="card"><h3>Same split. Different exam lengths.</h3><div class="table-wrap"><table><caption>Assessment at a glance</caption><thead><tr><th scope="col">Component</th><th scope="col">SL</th><th scope="col">HL</th><th scope="col">Weight</th></tr></thead><tbody><tr><th scope="row">Paper 1<br><small>1A: multiple choice<br>1B: data-based</small></th><td>1 h 30 min<br>45 marks</td><td>2 h<br>60 marks</td><td>36%</td></tr><tr><th scope="row">Paper 2<br><small>Short and extended responses</small></th><td>1 h 30 min<br>55 marks</td><td>2 h 30 min<br>90 marks</td><td>44%</td></tr><tr><th scope="row">Scientific investigation (IA)</th><td>10 h<br>24 marks</td><td>10 h<br>24 marks</td><td>20%</td></tr></tbody></table></div><p>External exams total <b>80%</b>: 3 hours at SL, 4 hours 30 minutes at HL. Calculators and a clean Physics data booklet are permitted in both papers. There is no Paper 3 in this guide’s assessment model.</p><p class="small muted">Guide pp. 62–65. Paper 1A and 1B share the stated Paper 1 time; they are completed together without interruptions.</p><h3>Your investigation, your question</h3><p>The IA is a quantitative investigation answering your own research question, reported individually in a maximum of <b>3,000 words</b> (specified exclusions apply). Your teacher assesses it; the IB externally moderates it. Data may come from practical work, databases or simulations, among other approaches.</p><div class="grid"><div class="tile"><strong>Research design · 6</strong><p>A focused question and a reproducible method.</p></div><div class="tile"><strong>Data analysis · 6</strong><p>Process and interpret data, including uncertainties.</p></div><div class="tile"><strong>Conclusion · 6</strong><p>Answer the question using your analysis and scientific context.</p></div><div class="tile"><strong>Evaluation · 6</strong><p>Explain limitations and realistic improvements.</p></div></div><p class="small muted">Guide pp. 68–75. Collaboration may be allowed under the guide’s conditions; the investigation and final report remain individual.</p></div>`,ids:[
numeric('external','What percentage of the final grade comes from external exams at either level?',80,'%','Paper 1 contributes 36% and Paper 2 contributes 44%: 80% in total. The IA is the remaining 20%.'),
mc('data','Where will you meet data-based questions in Paper 1?', ['Paper 1A','Paper 1B','Paper 3'],1,'Paper 1A is multiple choice; Paper 1B is data-based. Both are part of Paper 1.'),
numeric('hltime','What is the total HL external examination time, in minutes?',270,'minutes','Paper 1: 120 minutes. Paper 2: 150 minutes. Total: 270 minutes (4 hours 30 minutes).'),
mc('ia','Which would be the most promising starting point for an investigation?', ['Is physics interesting?','How does pendulum length affect its period at a small fixed release angle?','A group report copied from a textbook'],1,'This question links a measurable independent variable (length) with a dependent variable (period) and specifies a condition to control. It still needs a feasible method and thoughtful analysis.'),
mc('criteria','You discuss how timing by hand affected your results and suggest a light gate. Which criterion is the closest match?', ['Research design','Conclusion','Evaluation'],2,'Evaluation considers the impact of methodological weaknesses and limitations, and explains specific, realistic improvements.'),
numeric('wordlimit','What is the maximum overall word count for the individual IA report?',3000,'words','3,000 words is a maximum, not a target. The guide lists exclusions such as data tables, equations and references.') ]},
{title:'Calibrate your toolkit',short:'Units & prefixes',time:'12 min',kicker:'03 / CALIBRATION',intro:'A number without a unit is an unfinished measurement. Learn to move confidently between everyday units and the SI system.',content:()=>`
<div class="card"><h3>Seven base units. Many combinations.</h3><div class="table-wrap"><table><thead><tr><th scope="col">Quantity</th><th scope="col">SI base unit</th><th scope="col">Symbol</th></tr></thead><tbody>${[['Length','metre','m'],['Mass','kilogram','kg'],['Time','second','s'],['Electric current','ampere','A'],['Thermodynamic temperature','kelvin','K'],['Amount of substance','mole','mol'],['Luminous intensity','candela','cd']].map(r=>`<tr>${r.map((c,i)=>i===0?`<th scope="row">${c}</th>`:`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>Derived units combine base units: speed is m s<sup>−1</sup>; acceleration is m s<sup>−2</sup>; force is kg m s<sup>−2</sup>, named the newton (N).</p><h3>Prefixes are powers of ten</h3><p class="formula">G = 10⁹ · M = 10⁶ · k = 10³<br>c = 10⁻² · m = 10⁻³ · μ = 10⁻⁶ · n = 10⁻⁹</p><p>Case matters: <b>M</b> is mega, <b>m</b> is milli. The symbol m alone means metre; before a unit, as in ms, it means milli.</p><div class="tile"><strong>Worked example</strong><p>250 μs = 250 × 10⁻⁶ s = <b>2.50 × 10⁻⁴ s</b>.<br>For areas, square the conversion too: 1 cm² = (10⁻² m)² = <b>10⁻⁴ m²</b>.</p></div><p>On paper, write a conversion factor for each question before checking. You can enter scientific notation as <b>2.5e-4</b>.</p></div>`,ids:[
mc('mass','Which is the SI base unit of mass?', ['gram (g)','kilogram (kg)','newton (N)'],1,'The kilogram is the SI base unit of mass, even though its name already contains a prefix. The newton measures force.'),
numeric('mm','Convert 4.2 mm into metres.',.0042,'m','Milli means 10⁻³: 4.2 mm = 4.2 × 10⁻³ m = 0.0042 m.'),
numeric('micro','A sensor responds in 350 μs. Express this in seconds.',.00035,'s','Micro means 10⁻⁶: 350 × 10⁻⁶ = 3.50 × 10⁻⁴ s.'),
numeric('mega','Convert 2.4 MW into watts.',2400000,'W','Mega means 10⁶: 2.4 MW = 2.4 × 10⁶ W. The capital M matters.'),
numeric('area','A detector has an area of 12 cm². Convert it into m².',.0012,'m²','1 cm² = (0.01 m)² = 0.0001 m². So 12 cm² = 0.0012 m², not 0.12 m².'),
numeric('speed','A vehicle moves at 72 km/h. What is its speed in m/s?',20,'m/s','72 × 1000 ÷ 3600 = 20 m/s. Convert both the distance and the time.') ]},
{title:'Zoom through the universe',short:'Scale & estimates',time:'12 min',kicker:'04 / EXPLORATION',intro:'From atomic scales to astronomical distances, powers of ten let us compare things that are wildly different in size.',content:()=>`
<div class="card"><h3>Take the scale dial for a spin</h3><p>Change the exponent. Each step up multiplies the length by ten; each step down divides it by ten. Explore at least four stops and predict the size before revealing it.</p><div class="scale"><label for="scale-power">Length exponent: 10 to the power of…</label><div class="answer-line"><button class="btn secondary" id="scale-down" aria-label="Decrease exponent">−</button><input id="scale-power" type="number" min="-15" max="16" step="1" value="0"><button class="btn secondary" id="scale-up" aria-label="Increase exponent">+</button></div><output id="scale-output" for="scale-power" aria-live="polite"></output><p id="scale-example"></p></div><h3>Scientific notation</h3><p>Write a number as a × 10ⁿ, with 1 ≤ a &lt; 10. For example, 0.00072 m = <b>7.2 × 10⁻⁴ m</b>. To compare scales, divide the lengths; for powers of ten, subtract the exponents.</p><h3>Order of magnitude</h3><p>For this lesson, use the <b>nearest power of ten on a logarithmic scale</b>. For a × 10ⁿ, keep 10ⁿ when a &lt; √10 ≈ 3.16; otherwise choose 10ⁿ⁺¹. So 2 × 10³ has order 10³, while 8 × 10³ has order 10⁴. Stating the convention avoids ambiguity.</p><details><summary>Why 3.16 rather than 5?</summary><p>√10 is equally far from 1 and 10 by multiplication: 1 × √10 = √10 and √10 × √10 = 10. This is a logarithmic midpoint. Some contexts use a different rounding convention; this activity states its convention explicitly.</p></details><div class="tile"><strong>Estimate before you calculate</strong><p>How many heartbeats in a day? Assume 70 beats/minute. Then 70 × 60 × 24 ≈ 100,000 beats/day. The assumption matters; this is an estimate, not an exact count.</p></div><p class="small muted">Scientific notation and nearest-order estimates are course skills: <a href="physics-guide-2025.pdf#page=35" target="_blank" rel="noopener">guide p. 29 (PDF 35)</a>. The worked examples and scale dial are lesson activities.</p></div>`,ids:[
numeric('notation','Fill the exponent: 0.00072 m = 7.2 × 10ⁿ m. What is n?',-4,'','Move the decimal four places right to get 7.2, so the exponent is −4.'),
numeric('ratio','A cell is about 10⁻⁵ m across; an atom is about 10⁻¹⁰ m. How many times larger is the cell?',100000,'times','10⁻⁵ ÷ 10⁻¹⁰ = 10⁵ = 100,000. This compares linear size, not volume.'),
numeric('order','Using our nearest-power convention, 8 × 10⁶ m has order 10ⁿ m. What is n?',7,'','8 exceeds √10 ≈ 3.16, so the nearest logarithmic power is 10⁷ m.'),
numeric('heart','At an assumed 70 beats/minute, calculate the estimated number of heartbeats in 24 hours.',100800,'beats','70 × 60 × 24 = 100,800 beats. Given the rough rate, report roughly 100,000 beats, with order 10⁵.'),
mc('estimate','Estimate a classroom’s air volume. Which approach is defensible?', ['Multiply estimated length × width × height, and state the assumptions','Guess a large number and omit the unit','Multiply the floor area by the number of students'],0,'A room approximated as a rectangular box has V = length × width × height, in m³. For example, 8 m × 6 m × 3 m ≈ 140 m³; the dimensions are estimates.') ]},
{title:'Clear for launch',short:'Exit checkpoint',time:'6 min',kicker:'05 / DEBRIEF',intro:'Bring the course map and your new toolkit together. Check what you can explain without looking back, then reflect on what comes next.',content:()=>`<div class="card"><h3>Close your notes for a moment</h3><p>Try these three transfer questions first. Then write your own short debrief below. If you have 5–10 minutes left, the optional dimensional-analysis mission is ready.</p></div>`,ids:[
mc('exitia','A friend says: “The IA only matters at HL.” What should you tell them?', ['Correct: SL has only exams','The IA is 20% at both levels and uses the same criteria','The IA replaces Paper 2 at SL'],1,'Both SL and HL complete a scientific investigation worth 20%, assessed against the same four criteria.'),
numeric('exitnm','A wavelength is 600 nm. Express it in metres.',.0000006,'m','Nano means 10⁻⁹. 600 × 10⁻⁹ m = 6.00 × 10⁻⁷ m.'),
mc('exitarea','You double every edge of a cube. What happens to its volume?', ['It doubles','It becomes four times larger','It becomes eight times larger'],2,'Volume scales with length cubed: 2³ = 8. Always distinguish length, area and volume when comparing scales.') ]},
{title:'The equation detective',short:'Bonus: dimensions',time:'5–10 min · optional',kicker:'BONUS / DEEP SPACE',intro:'Can an equation be wrong before you put any numbers in? Dimensions give you a powerful first check. Open to both SL and HL.',content:()=>`<div class="card"><h3>Check the kind of quantity</h3><p>Dimensions describe physical quantities: length [L], mass [M] and time [T]. Units describe how we measure them: metres, kilograms and seconds. Metres and kilometres both have dimension [L].</p><p class="formula">[speed] = L T⁻¹<br>[acceleration] = L T⁻²<br>[force] = M L T⁻²</p><p>Terms added together must have the same dimensions. Both sides of an equation must match. Pure numbers such as ½ and 2π have no dimensions.</p><div class="tile"><strong>Test: s = ut + ½at²</strong><p>[ut] = (L T⁻¹)(T) = L<br>[at²] = (L T⁻²)(T²) = L<br>Both terms are lengths, so the equation passes the dimensional check.</p></div><p>A dimensional match is <b>necessary but not sufficient</b>: it cannot prove an equation is physically correct or determine a numerical factor.</p></div>`,ids:[
mc('dimwrong','Which proposed equation for distance s fails the dimensional check? (v = speed, a = acceleration, t = time)', ['s = vt','s = at','s = ½at²'],1,'at has dimension (L T⁻²)(T) = L T⁻¹, which is speed, not length.'),
mc('pendulum','Which expression could have the dimensions of a pendulum period? (ℓ = length, g = acceleration)', ['√(ℓ/g)','ℓ/g','√(g/ℓ)'],0,'[ℓ/g] = L ÷ (L T⁻²) = T², so its square root has dimension T. Dimensions alone cannot supply the factor 2π or the physical assumptions.'),
mc('dimproof','Both E = mv² and E = ½mv² have the dimensions of energy. What does this tell us?', ['Both must be correct for kinetic energy','Dimensions cannot distinguish their numerical factors','Energy has no units'],1,'Dimensional analysis cannot distinguish dimensionless constants. For non-relativistic kinetic energy the factor is ½; physics, not dimensions alone, establishes it.') ]}
];
const main = document.getElementById('main');
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function save() { try { localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); } catch { storageAvailable=false; } if(!storageAvailable) document.getElementById('storage-note').textContent='Browser storage is unavailable. Keep this tab open; progress will not survive a reload.'; }
function complete(i) { return missions[i].ids.every(id=>state.solved[id] === true); }
function renderNav() {
 const stamps=missions.slice(0,5).filter((_,i)=>complete(i)).length;
 document.getElementById('progress-text').textContent=`${stamps} of 5 stamps`;
 document.getElementById('progress').value=stamps;
 document.getElementById('missions').innerHTML=missions.map((m,i)=>`<button type="button" data-mission="${i}" ${state.mission===i?'aria-current="step"':''}><span class="num">${complete(i)?'✓':i===5?'+':String(i+1).padStart(2,'0')}</span><span>${m.short}<small>${m.time}${complete(i)?' · complete':''}</small></span></button>`).join('');
 document.querySelectorAll('[data-mission]').forEach(b=>b.addEventListener('click',()=>navigate(Number(b.dataset.mission))));
}
function questionHtml(id,index) { const q=questions[id]; return `<section class="question" id="q-${id}" aria-labelledby="label-${id}"><h3 id="label-${id}">${index+1}. ${q.prompt}</h3><form data-question="${id}">${q.type==='mc'?`<div class="options" role="radiogroup" aria-labelledby="label-${id}">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="${id}" value="${i}" ${String(state.answers[id])===String(i)?'checked':''}><span>${o}</span></label>`).join('')}</div>`:`<div class="answer-line"><input type="number" step="any" name="${id}" aria-labelledby="label-${id}" aria-describedby="unit-${id}" value="${escapeHtml(state.answers[id])}" placeholder="Your answer"><span id="unit-${id}">${q.unit}</span></div>`}<button class="btn check" type="submit">Check answer</button><div class="feedback ${state.solved[id]?'good':''}" id="feedback-${id}" role="status" aria-live="polite">${state.solved[id]?`<b>Stamp secured.</b> ${q.explanation}`:''}</div></form></section>`; }
function render() {
 const m=missions[state.mission]; renderNav();
 main.innerHTML=`<section class="mission-head"><div class="mission-meta"><span class="pill">${m.time}</span><span class="pill">${state.mission===5?'Extra challenge':'Self-directed · SL + HL'}</span></div><span class="tag">${m.kicker}</span><h2>${m.title}</h2><p>${m.intro}</p></section>${m.content()}<div class="card"><h3>Check your bearings</h3><p class="muted">Unlimited retries. Read each explanation and correct your reasoning.</p>${m.ids.map(questionHtml).join('')}</div>${state.mission===4?reflectionHtml():''}<div class="card" id="mission-status" role="status"></div><div class="actions">${state.mission>0?'<button class="btn secondary" id="previous">Previous mission</button>':'<span class="muted">Aim for about 50 minutes in total.</span>'}${state.mission<5?`<button class="btn" id="next">${state.mission===4?'Try the optional challenge →':'Next mission →'}</button>`:'<button class="btn" id="back-exit">Return to debrief →</button>'}</div>`;
 main.querySelectorAll('form[data-question]').forEach(form=>{form.addEventListener('submit',checkAnswer);form.addEventListener('input',()=>{const id=form.dataset.question; const data=new FormData(form); state.answers[id]=data.get(id)??'';save();});});
 document.getElementById('previous')?.addEventListener('click',()=>navigate(state.mission-1));
 document.getElementById('next')?.addEventListener('click',()=>navigate(state.mission+1));
 document.getElementById('back-exit')?.addEventListener('click',()=>navigate(4));
 if(state.mission===3) setupScale();
 if(state.mission===4) setupReflection();
 updateStatus(); save();
}
function navigate(i) { state.mission=i;save();render();main.focus({preventScroll:true});main.scrollIntoView({block:'start',behavior:'instant'}); }
function checkAnswer(event) {
 event.preventDefault();const form=event.currentTarget;const id=form.dataset.question;const q=questions[id];const raw=new FormData(form).get(id);const feedback=document.getElementById(`feedback-${id}`);
 if(raw===null || String(raw).trim()==='' || !Number.isFinite(Number(raw))) { feedback.className='feedback retry';feedback.textContent='Choose or enter an answer first.';return; }
 state.answers[id]=raw;
 const correct=q.type==='mc'?Number(raw)===q.correct:Math.abs(Number(raw)-q.correct)<=Math.max(Math.abs(q.correct)*1e-9,1e-14);
 if(correct) state.solved[id]=true;
 feedback.className=`feedback ${correct?'good':'retry'}`;
 feedback.innerHTML=correct?`<b>Correct. ${state.mission===5?'Good detective work!':'Signal received!'}</b> ${q.explanation}`:`<b>Not quite—try again.</b> ${q.explanation}${state.solved[id]?' Your earlier completion stamp is retained.':''}`;
 save();renderNav();updateStatus();
}
function updateStatus() { const m=missions[state.mission]; const remaining=m.ids.filter(id=>!state.solved[id]).length;document.getElementById('mission-status').innerHTML=remaining?`<b>${remaining} check${remaining===1?'':'s'} to go for this stamp.</b> You can revisit any mission; nothing is locked.`:`<span class="stamp">✓ ${state.mission===5?'Bonus':'Mission'} stamp earned</span><p>${state.mission===4?(missions.slice(0,5).every((_,i)=>complete(i))?'All five stamps collected. Finish your reflection below the questions, then explore the bonus if you have time.':'Exit questions complete. Check the mission list for any earlier stamps still to earn and finish your reflection.'):'Before moving on, explain one idea from this mission in your own words.'}</p>`; }
function reflectionHtml() { return `<section class="card reflection"><h3>Your launch log</h3><p>Spend 3 minutes here. These reflections are for you; they are not automatically marked or submitted. You can copy the log to share later.</p>${[['learned','One course fact I can now explain…'],['reasoning','One conversion or estimate, including my reasoning…'],['wonder','One question I want to ask next lesson…']].map(([id,label])=>`<label for="note-${id}">${label}</label><textarea id="note-${id}" data-note="${id}" placeholder="Use your own words…">${escapeHtml(state.notes[id])}</textarea>`).join('')}<div class="actions"><button class="btn secondary" id="copy-log">Copy my launch log</button><button class="btn secondary" id="print-log">Print this debrief</button></div><p id="copy-status" role="status"></p></section>`; }
function setupReflection() { main.querySelectorAll('[data-note]').forEach(el=>el.addEventListener('input',()=>{state.notes[el.dataset.note]=el.value;save();}));document.getElementById('print-log').addEventListener('click',()=>window.print());document.getElementById('copy-log').addEventListener('click',async()=>{const text=`Physics Launch Lab\n${missions.slice(0,5).map((m,i)=>`${complete(i)?'✓':'○'} ${m.short}`).join('\n')}\n\n${['learned','reasoning','wonder'].map(id=>`${document.querySelector(`label[for="note-${id}"]`).textContent}\n${state.notes[id]||'(not written)'}`).join('\n\n')}`;try{await navigator.clipboard.writeText(text);document.getElementById('copy-status').textContent='Launch log copied. Paste it into your own notes or class platform.';}catch{document.getElementById('copy-status').textContent='Copy is unavailable here. Select and copy your reflections manually, or print the debrief.';}}); }
function setupScale() {
 const examples={'-15':'A femtometre: a nuclear length scale.','-10':'An ångström: a typical atomic size scale.','-6':'A micrometre: a bacterial size scale.','-3':'A millimetre: roughly the thickness of a bank card.','0':'A metre: an everyday human length scale.','3':'A kilometre: a neighbourhood walk.','7':'Ten thousand kilometres: roughly the diameter of Earth.','11':'One hundred billion metres: roughly the Earth–Sun distance scale.','16':'Ten quadrillion metres: roughly one light-year.'};
 const input=document.getElementById('scale-power');
 function update(){const n=Number(input.value);if(input.value===''||!Number.isInteger(n)||n< -15||n>16){document.getElementById('scale-output').textContent='Choose an integer from −15 to 16.';document.getElementById('scale-example').textContent='';return;}document.getElementById('scale-output').innerHTML=`10<sup>${n}</sup> m`;const nearest=Object.keys(examples).map(Number).sort((a,b)=>Math.abs(a-n)-Math.abs(b-n))[0];document.getElementById('scale-example').innerHTML=examples[n]||`This is ${n>nearest?`10<sup>${n-nearest}</sup> times larger than`:`1 / 10<sup>${nearest-n}</sup> of`} the nearby 10<sup>${nearest}</sup> m reference. ${examples[nearest]}`;}
 input.addEventListener('input',update);document.getElementById('scale-down').addEventListener('click',()=>{input.value=Math.max(-15,Math.min(16,Number(input.value)||0)-1);update();});document.getElementById('scale-up').addEventListener('click',()=>{input.value=Math.min(16,Math.max(-15,Number(input.value)||0)+1);update();});update();
}
render();
