// AQA GCSE Physics 8463-style prompts grouped by typing difficulty.
// Keep terms concise; definitions appear as hints in later rounds.
export const EASY_WORDS = [
  { term: 'force', definition: 'A push or pull that may change speed, shape or direction' },
  { term: 'mass', definition: 'The amount of matter in an object, measured in kilograms' },
  { term: 'weight', definition: 'The force on a mass due to gravity' },
  { term: 'speed', definition: 'Distance travelled per unit time' },
  { term: 'distance', definition: 'How far an object has moved' },
  { term: 'time', definition: 'The measured interval between two events' },
  { term: 'energy', definition: 'A quantity stored and transferred by systems' },
  { term: 'joule', definition: 'The unit of energy and work done' },
  { term: 'power', definition: 'The rate at which energy is transferred' },
  { term: 'watt', definition: 'The unit of power, equal to one joule per second' },
  { term: 'current', definition: 'The rate of flow of electric charge' },
  { term: 'charge', definition: 'A property of matter measured in coulombs' },
  { term: 'voltage', definition: 'Energy transferred per unit charge' },
  { term: 'resistance', definition: 'How much a component opposes current' },
  { term: 'circuit', definition: 'A complete path that electric current can flow around' },
  { term: 'series', definition: 'A circuit path with components one after another' },
  { term: 'parallel', definition: 'A circuit with branches for current to split' },
  { term: 'density', definition: 'Mass per unit volume' },
  { term: 'pressure', definition: 'Force per unit area' },
  { term: 'atom', definition: 'The smallest particle of an element' },
  { term: 'nucleus', definition: 'The small central part of an atom' },
  { term: 'proton', definition: 'A positively charged particle in the nucleus' },
  { term: 'neutron', definition: 'An uncharged particle in the nucleus' },
  { term: 'electron', definition: 'A negatively charged particle around the nucleus' },
  { term: 'isotope', definition: 'Atoms of the same element with different numbers of neutrons' },
  { term: 'alpha', definition: 'A type of nuclear radiation made of two protons and two neutrons' },
  { term: 'beta', definition: 'A type of nuclear radiation made of a fast moving electron' },
  { term: 'gamma', definition: 'A high frequency electromagnetic wave from the nucleus' },
  { term: 'wave', definition: 'A disturbance that transfers energy' },
  { term: 'sound', definition: 'A longitudinal wave caused by vibrations' },
  { term: 'light', definition: 'Electromagnetic radiation visible to the eye' },
  { term: 'ray', definition: 'A line showing the direction light travels' },
  { term: 'magnet', definition: 'An object that produces a magnetic field' },
  { term: 'pole', definition: 'A place on a magnet where the force is strongest' },
  { term: 'field', definition: 'A region where a non-contact force acts' },
  { term: 'orbit', definition: 'The curved path of an object around a star, planet or moon' },
];

export const MEDIUM_WORDS = [
  { term: 'energy store', definition: 'A way energy is held before or after a transfer' },
  { term: 'kinetic store', definition: 'The energy store of a moving object' },
  { term: 'thermal store', definition: 'The energy store linked to object temperature' },
  { term: 'elastic store', definition: 'The energy store of a stretched or compressed object' },
  { term: 'work done', definition: 'Energy transferred when a force moves an object' },
  { term: 'efficiency', definition: 'Useful energy output divided by total energy input' },
  { term: 'renewable', definition: 'An energy resource that can be replaced as it is used' },
  { term: 'non renewable', definition: 'An energy resource that will run out' },
  { term: 'national grid', definition: 'The network transferring electricity from power stations to users' },
  { term: 'potential difference', definition: 'Energy transferred per unit charge between two points' },
  { term: 'ohmic conductor', definition: 'A conductor with current proportional to potential difference' },
  { term: 'filament lamp', definition: 'A lamp whose resistance rises as temperature increases' },
  { term: 'thermistor', definition: 'A resistor whose resistance changes with temperature' },
  { term: 'ldr', definition: 'A resistor whose resistance changes with light intensity' },
  { term: 'live wire', definition: 'The mains wire at high potential difference' },
  { term: 'earth wire', definition: 'A safety wire that can carry fault current to ground' },
  { term: 'change of state', definition: 'A change between solid, liquid and gas' },
  { term: 'latent heat', definition: 'Energy for a change of state with no temperature change' },
  { term: 'internal energy', definition: 'Total kinetic and potential energy of particles' },
  { term: 'gas pressure', definition: 'Force per unit area from particles colliding with walls' },
  { term: 'half life', definition: 'Time for activity or count rate to halve' },
  { term: 'activity', definition: 'The rate at which unstable nuclei decay' },
  { term: 'irradiation', definition: 'Exposure to radiation from a source outside the body' },
  { term: 'contamination', definition: 'Unwanted radioactive material on or inside an object' },
  { term: 'resultant force', definition: 'The single force with the same effect as all forces combined' },
  { term: 'friction', definition: 'A force opposing motion between surfaces' },
  { term: 'momentum', definition: 'Mass multiplied by velocity' },
  { term: 'acceleration', definition: 'Rate of change of velocity' },
  { term: 'extension', definition: 'Increase in length of a stretched object' },
  { term: 'hooke\'s law', definition: 'Extension is proportional to force until the limit is reached' },
  { term: 'stopping distance', definition: 'Thinking distance plus braking distance' },
  { term: 'reaction time', definition: 'Time taken to respond to a stimulus' },
  { term: 'scalar', definition: 'A quantity with magnitude only' },
  { term: 'vector', definition: 'A quantity with magnitude and direction' },
  { term: 'frequency', definition: 'Number of complete waves passing a point each second' },
  { term: 'wavelength', definition: 'Distance from a point on one wave to the same point on the next' },
  { term: 'amplitude', definition: 'Maximum displacement from the undisturbed position' },
  { term: 'transverse wave', definition: 'A wave with oscillations perpendicular to energy transfer' },
  { term: 'longitudinal wave', definition: 'A wave with oscillations parallel to energy transfer' },
  { term: 'refraction', definition: 'Change of direction when a wave changes speed at a boundary' },
  { term: 'diffraction', definition: 'Spreading of waves through gaps or around obstacles' },
  { term: 'magnetic field', definition: 'The region where a magnetic material experiences a force' },
  { term: 'electromagnet', definition: 'A magnet produced by current in a coil' },
  { term: 'motor effect', definition: 'Force on a current-carrying wire in a magnetic field' },
  { term: 'red shift', definition: 'Increase in wavelength from a galaxy moving away' },
];

export const HARD_WORDS = [
  { term: 'gravitational store', definition: 'Energy stored by an object raised in a gravitational field' },
  { term: 'kinetic energy', definition: 'Half times mass times speed squared' },
  { term: 'elastic potential', definition: 'Energy stored when an object is stretched or compressed' },
  { term: 'specific heat capacity', definition: 'Energy to raise one kilogram by one degree Celsius' },
  { term: 'specific latent heat', definition: 'Energy needed to change state for one kilogram' },
  { term: 'static electricity', definition: 'Charge build-up caused by electrons moving between insulators' },
  { term: 'electric field', definition: 'A region where a charged object experiences a force' },
  { term: 'series circuit', definition: 'Circuit where current is the same through all components' },
  { term: 'parallel circuit', definition: 'Circuit where potential difference is the same across branches' },
  { term: 'mains electricity', definition: 'Alternating potential difference supplied to homes' },
  { term: 'nuclear fission', definition: 'Splitting a large unstable nucleus into smaller nuclei' },
  { term: 'nuclear fusion', definition: 'Joining small nuclei to form a larger nucleus' },
  { term: 'chain reaction', definition: 'Fission neutrons causing more nuclei to split' },
  { term: 'background radiation', definition: 'Ionising radiation always present from natural and artificial sources' },
  { term: 'terminal velocity', definition: 'Constant velocity when driving and resistive forces balance' },
  { term: 'inertial mass', definition: 'Measure of how difficult it is to change velocity' },
  { term: 'conservation of momentum', definition: 'Total momentum before a collision equals total momentum after' },
  { term: 'centre of mass', definition: 'The point where the mass of an object may be considered concentrated' },
  { term: 'thinking distance', definition: 'Distance travelled during the driver reaction time' },
  { term: 'braking distance', definition: 'Distance travelled while brakes slow the vehicle' },
  { term: 'electromagnetic wave', definition: 'A transverse wave that transfers energy through fields' },
  { term: 'wave equation', definition: 'Wave speed equals frequency multiplied by wavelength' },
  { term: 'critical angle', definition: 'Angle of incidence that gives refraction along the boundary' },
  { term: 'total internal reflection', definition: 'Complete reflection when incidence angle is above the critical angle' },
  { term: 'electromagnetic spectrum', definition: 'All electromagnetic waves arranged by wavelength or frequency' },
  { term: 'ultraviolet', definition: 'Electromagnetic radiation with shorter wavelength than visible light' },
  { term: 'infrared', definition: 'Electromagnetic radiation emitted by warm objects' },
  { term: 'magnetic flux density', definition: 'Magnetic field strength measured in tesla' },
  { term: 'generator effect', definition: 'Potential difference induced by changing magnetic field' },
  { term: 'transformer', definition: 'Device changing alternating potential difference using induction' },
  { term: 'step up transformer', definition: 'Transformer that increases potential difference' },
  { term: 'step down transformer', definition: 'Transformer that decreases potential difference' },
  { term: 'orbital speed', definition: 'Speed needed for a stable orbit at a given radius' },
  { term: 'life cycle star', definition: 'Sequence of stages a star passes through' },
  { term: 'main sequence', definition: 'Stable star stage where fusion balances gravity' },
  { term: 'big bang', definition: 'Theory that the universe began from a very hot dense state' },
];

export const ALL_WORDS = [...EASY_WORDS, ...MEDIUM_WORDS, ...HARD_WORDS];
